### ISSUE TITLE
Recast not installed imports statment node

### ISSUE THREAD

**Issue by donaldboulton** [getfullog/gatsby-plugin-static-props#1]
Was hoping to use this good idea 3 errors

On a windows machine .fs will not install use fs-extra

add recast to package json

change import statement

ERROR

`ERROR #11321  PLUGIN

"gatsby-plugin-static-props" threw an error while running the onCreatePage lifecycle:

Cannot use import statement outside a module

  22 |   require("jsdom-global")()
  23 |
> 24 |   const PageComponent = require(page.component)
     |                         ^
  25 |   const getStaticProps = PageComponent.getStaticProps || new Function()
  26 |
  27 |   try {

File: node_modules\gatsby-plugin-static-props\gatsby-node.js:24:25`

**Comment by sashasushko** [comment]
@victorvoid could you please republish npm package? There is old version in npm, without `recast`

**Comment by victorvoid** [comment]
Thanks!! Published ✌🏻

**Comment by donaldboulton** [comment]
Thank You!
